steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['ci', '--only=production']

  # Build React app
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/quotify-web', '.']

  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quotify-web']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'quotify-web'
      - '--image=gcr.io/$PROJECT_ID/quotify-web'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--timeout=3600'
      - '--port=5174'
      - '--max-instances=10'

images:
  - 'gcr.io/$PROJECT_ID/quotify-web'

timeout: '1200s'